kafka:
  pool: nav-dev
cluster: dev-gcp
endpoints:
  pdl: https://pdl-api.dev-fss-pub.nais.io/graphql
  pdf: http://tiltakspenger-pdfgen
  joark: https://dokarkiv.dev-fss-pub.nais.io
  tiltakspengerarena: https://tiltakspenger-arena.dev-fss-pub.nais.io
  tiltakspengertiltak: http://tiltakspenger-tiltak
  av: http://clamav.nais-system/scan
  tiltak: http://tiltakspenger-tiltak
outboundExternalUrls:
  pdl: pdl-api.dev-fss-pub.nais.io
  dokarkiv: dokarkiv.dev-fss-pub.nais.io
  tiltakspengerarena: tiltakspenger-arena.dev-fss-pub.nais.io
audience:
  pdl: dev-fss:pdl:pdl-api
  joark: dev-fss:teamdokumenthandtering:dokarkiv
  tiltakspengerarena: dev-fss:tpts:tiltakspenger-arena
  tiltakspengertiltak: dev-gcp:tpts:tiltakspenger-tiltak
scope:
  pdl: api://dev-fss.pdl.pdl-api/.default
  joark: api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default
unleash:
  environment: development
sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: false
  tier: db-f1-micro
