kafka:
  pool: nav-prod
cluster: prod-gcp
endpoints:
  pdl: https://pdl-api.prod-fss-pub.nais.io/graphql
  pdf: http://tiltakspenger-pdfgen
  joark: https://dokarkiv.prod-fss-pub.nais.io
  tiltakspengerarena: https://tiltakspenger-arena.prod-fss-pub.nais.io
  tiltakspengertiltak: http://tiltakspenger-tiltak
  tiltakspengervedtak: http://tiltakspenger-saksbehandling-api
  av: http://clamav.nais-system/scan
outboundExternalUrls:
  pdl: pdl-api.prod-fss-pub.nais.io
  dokarkiv: dokarkiv.prod-fss-pub.nais.io
  tiltakspengerarena: tiltakspenger-arena.prod-fss-pub.nais.io
audience:
  pdl: prod-fss:pdl:pdl-api
  joark: prod-fss:teamdokumenthandtering:dokarkiv
  tiltakspengerarena: prod-fss:tpts:tiltakspenger-arena
  tiltakspengertiltak: prod-gcp:tpts:tiltakspenger-tiltak
scope:
  pdl: api://prod-fss.pdl.pdl-api/.default
  joark: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
  vedtak: api://prod-gcp.tpts.tiltakspenger-saksbehandling-api/.default
sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: true
  tier: db-custom-1-3840