apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-soknad-api
  namespace: tpts
  labels:
    team: tpts
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    config.linkerd.io/proxy-outbound-connect-timeout: 3000ms
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 2
  kafka:
    pool: {{ kafka.pool }}
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  leaderElection: true
  gcp:
    sqlInstances:
      - name: tiltakspenger-soknad-api
        type: POSTGRES_15
        tier: {{ sqlInstances.tier }}
        diskAutoresize: {{ sqlInstances.diskAutoresize }}
        pointInTimeRecovery: {{ sqlInstances.pointInTimeRecovery }}
        databases:
          - name: soknad
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: tiltakspenger-soknad
          namespace: tpts
          cluster: {{ cluster }}
    outbound:
      rules:
        - application: tiltakspenger-tiltak
        - application: tiltakspenger-pdfgen
        - application: tiltakspenger-saksbehandling-api
        - application: clamav
          namespace: nais-system
      external:
        - host: {{outboundExternalUrls.pdl}}
        - host: {{outboundExternalUrls.dokarkiv}}
        - host: {{outboundExternalUrls.tiltakspengerarena}}
  env:
    - name: PDL_ENDPOINT_URL
      value: {{ endpoints.pdl }}
    - name: PDL_AUDIENCE
      value: {{ audience.pdl }}
    - name: PDL_SCOPE
      value: {{ scope.pdl }}
    - name: JOARK_ENDPOINT_URL
      value: {{ endpoints.joark }}
    - name: JOARK_AUDIENCE
      value: {{ audience.joark }}
    - name: JOARK_SCOPE
      value: {{ scope.joark }}
    - name: VEDTAK_SCOPE
      value: {{ scope.vedtak }}
    - name: PDF_ENDPOINT_URL
      value: {{ endpoints.pdf }}
    - name: AV_ENDPOINT_URL
      value: {{ endpoints.av }}
    - name: TILTAKSPENGER_ARENA_ENDPOINT_URL
      value: {{ endpoints.tiltakspengerarena }}
    - name: TILTAKSPENGER_VEDTAK_ENDPOINT_URL
      value: {{ endpoints.tiltakspengervedtak }}
    - name: TILTAKSPENGER_ARENA_AUDIENCE
      value: {{ audience.tiltakspengerarena }}
    - name: TILTAKSPENGER_TILTAK_ENDPOINT_URL
      value: {{ endpoints.tiltakspengertiltak }}
    - name: TILTAKSPENGER_TILTAK_AUDIENCE
      value: {{ audience.tiltakspengertiltak }}
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
